default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
# -   repo: https://github.com/kynan/nbstripout
#     rev: 0.3.9
#     hooks:
#     -   id: nbstripout
#         language_version: python3
#         files: ".ipynb"
