default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: setup.cfg
      - id: end-of-file-fixer
        exclude: setup.cfg
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--target-version", "py39"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
#-   repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: v1.4.4
#    hooks:
#    -   id: autopep8
#        args: ['--global-config=setup.cfg','--in-place']
#-   repo: https://github.com/timothycrosley/isort
#    rev: 5.6.4
#    hooks:
#    -   id: isort
#        args: ['--profile', 'black']
#-   repo: https://github.com/pycqa/pydocstyle
#    rev: 5.0.2
#    hooks:
#    -   id: pydocstyle
#        args: ["--conventions=numpy"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
# -   repo: https://github.com/kynan/nbstripout
#     rev: 0.3.9
#     hooks:
#     -   id: nbstripout
#         language_version: python3
#         files: ".ipynb"
