name: rook-dev
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.13
  # development
  - bump-my-version >=0.26.0
  - coverage >=7.5.0
  - cruft >=2.15.0
  - flit >=3.9.0,<4.0
  - nbsphinx >=0.9.5
  - nbval >=0.10.0
  - ruff >=0.5.7
  - sphinx >=7.0.0
  - tox >=4.18.0
  - watchdog >=4.0.0
  # tests
  - pytest >=8.0.0
  - pytest-cov >=5.0.0
  - pytest-timeout >=2.3.1
  - beautifulsoup4 >4.12.3
