# conda env create -f environment-docs.yml
name: rook
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.10
  - pywps >=4.5.2,<4.7
  - sphinx >=7.0.0
  - nbsphinx >=0.9.5
  - ipython >=8.13.0
