name: Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "src/rook/__version__.py"
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  # For a given workflow, if we push to the same branch, cancel all previous builds on that branch except on master.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read


jobs:
  build-publish:
    name: Test and Publish image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: roocs/rook
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Gather Docker metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Build Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          cache-to: type=gha,mode=max
          file: Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          load: true
          push: false
          tags: ${{ env.IMAGE_NAME }}:test

      - name: Inspect image labels
        run: |
          docker inspect --format='{{json .Config.Labels}}' ${{ env.IMAGE_NAME }}:test

      - name: Run Docker image
        run: |
          docker run -d --name rook-test -p 5000:5000 ${{ env.IMAGE_NAME }}:test
          sleep 5
          curl -fsS "http://localhost:5000/wps?service=WPS&version=1.0.0&request=GetCapabilities" > /dev/null
          docker logs rook-test
          docker rm -f rook-test

      - name: Publish image to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}  # Never push image for pull requests
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          cache-from: type=gha
          file: Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
